#!/bin/bash

SETTINGS_FILE="bashrc bash_rc inputrc gitconfig screenrc vimrc vim tmux.conf"

if [ -d .git ]; then
    git submodule update --init
fi

for config in ${SETTINGS_FILE}; do
    ln -sf ${PWD}/${config} ${HOME}/.${config}
done

ln -sf ${PWD}/bin ${HOME}/bin
