#!/bin/bash
set -e

# install docker client
mkdir -p /tmp/docker-release
curl -sSL https://get.docker.com/builds/`uname -s`/`uname -m`/docker-1.13.0.tgz | tar -zxf - -C /tmp/docker-release
find /tmp/docker-release -name 'docker' -type f -perm '-u=x' -exec mv -i {} /usr/local/bin \;
rm -rf /tmp/docker-release

# install docker-compose for local service stack orchestration
curl -sSL https://github.com/docker/compose/releases/download/1.10.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# install docker-machine
curl -L https://github.com/docker/machine/releases/download/v0.9.0/docker-machine-`uname -s`-`uname -m` > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine
