#!/bin/bash
set -e

# install etcdctl
curl -sSL https://github.com/coreos/etcd/releases/download/v2.3.5/etcd-v2.3.5-linux-amd64.tar.gz | tar \
    --transform "s@etcd-v2.3.5-linux-amd64@./@" \
    -zxf - -C /usr/local/bin -- etcd-v2.3.5-linux-amd64/etcdctl

# install confd
curl -sSL https://github.com/kelseyhightower/confd/releases/download/v0.12.0-alpha3/confd-0.12.0-alpha3-linux-amd64 >/usr/local/bin/confd
chmod +x /usr/local/bin/confd

# setup default confd backend config dir
mkdir -p /etc/confd

# install google cloud sdk
export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" >/etc/apt/sources.list.d/google-cloud-sdk.list
curl -sL https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
apt-get update && apt-get install -y google-cloud-sdk
