#!/bin/bash
set -e

# install nodejs
curl -sL https://deb.nodesource.com/setup_4.x | /bin/bash -
apt-get update && apt-get install -y nodejs

# install common node packages
npm install -g \
    bower \
    gulp-cli \
    mustache \
    typescript
