#!/bin/bash
set -e

# install golang pacakge
curl -sSL https://storage.googleapis.com/golang/go1.7.3.linux-amd64.tar.gz | tar \
    -C /usr/local \
    -zxf -

echo "export GOROOT=/usr/local/go" >>~/.workspaceenv/bash_env
echo "export GOPATH=${HOME}/go" >>~/.workspaceenv/bash_env
echo "export PATH=${HOME}/go/bin:/usr/local/go/bin:${PATH}" >>~/.workspaceenv/bash_env
