#!/bin/bash
set -e

# install docker client
mkdir -p /tmp/docker-release
curl -sSL https://download.docker.com/`uname -s | tr '[:upper:]' '[:lower:]'`/static/stable/`uname -m`/docker-17.06.0-ce.tgz | tar -zxf - -C /tmp/docker-release
find /tmp/docker-release -name 'docker' -type f -perm '-u=x' -exec mv -i {} /usr/local/bin \;
rm -rf /tmp/docker-release

# install docker-compose for local service stack orchestration
curl -sSL https://github.com/docker/compose/releases/download/1.14.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# install docker-machine
curl -L https://github.com/docker/machine/releases/download/v0.12.1/docker-machine-`uname -s`-`uname -m` > /usr/local/bin/docker-machine
chmod +x /usr/local/bin/docker-machine
